# Run this command: docker compose up -d
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - grafana
  postgressql:
    image: postgres:16
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - database_storage:/var/lib/postgresql/data
    networks:
      - grafana
volumes:
  grafana_storage: {}
  database_storage: {}
networks:
  grafana: